### ISSUE TITLE
Use my Haskell package, don't copy/paste my code inside

### ISSUE THREAD

**Issue by MichelBoucey** [arowM/haskell-google-server-api#4]
I'm the author of the `google-oauth2-jwt` package which is open-sourced on `Hackage` and `Stackage`.

I'm sure you know that the honest way to use open-sourced code is to use the package you are interested in, not to, as you say, ["borrow" the code](https://github.com/arowM/haskell-google-server-api/blob/master/src/Google/JWT.hs) inside this package, which is the hard work of another one. _It is just plagiarism._

Why don't you "borrow" other packages, `unordered-containers` or `wai` and `wai-extra` packages ? Why not? My code is at the core of the so-called "your work". You should ironically ["star" my google-oauth2-jwt package](https://github.com/MichelBoucey/google-oauth2-jwt), don't you?

**It is a rule of Open Source, as in all intellectual work areas, to be fair enough to not copy/paste the work of another one.**

So please, be kind, and elegant enough, to use my package.

_N.B._ : `Copyright Kadzuya Okamoto (c) 2018`... You seems to believe in [Open Source LICENSE](https://github.com/arowM/haskell-google-server-api/blob/master/LICENSE), don't you? So, respect others.

**Comment by arowM** [comment]
I'm sorry I made you feel bad, but please see the [LICENSE file](https://github.com/arowM/haskell-google-server-api/blob/master/LICENSE#L36) of this library you referred in your comment again carefully. I have clearly indicated your license in the file. It has been here from [Initial commit](https://github.com/arowM/haskell-google-server-api/commit/faaab60cfbcf4511b4c134463e6f56c83367af56).
I'm not a professional for the rule of Open Source so I don't know if this is sufficient, but at least it doesn't suggest that I am plagiarizing with malicious intent.

Also, I have a reason I didn't make your "google-oauth2-jwt" a dependent library. It is because it wasn't enough to use the functions and types that your library exports. I had to rewrite the code you had written to achieve my goal. If you know a better way to achieve my goal, please let me know.

Or maybe I'm misusing the word "borrow". I am not a native English speaker, so I do not know the correct meaning of the word "borrow". That may be the reason why it made you feel uncomfortable.

I intended to use the word "borrow" to explicitly indicate that:

* Most of this code was written by you, not by me.
* I appreciate and respect you for achieving my goal that were not possible by me alone.
* I have made a few tweaks to suit what I want to achieve.


It is not my intention to make you feel uncomfortable, as you helped me back then with google-auth2-jwt.
I may have been inadequate.
Please let me know what you want me to do again after knowing the above facts.

**Comment by MichelBoucey** [comment]
I didn't saw you copy my license. It is the most important indeed. My bad. For me it is enough to close this issue.

But, for your information, despite the fact you did quite honestly things, you still did things a very wrong way.

In the BSD3 license, it was written that:

"Neither the name of Author Michel Boucey nor the names of other
      contributors may be used to endorse or promote products derived
      from this software without **specific prior written permission**."

I think it's clear enough. I didn't know you were using my code, I found it by myself. It is unpleasant.

You are certainly not as naive as your answer and your behavior seems to be. I'm quite sure you know how to develop with open-sourced code, as, at least, you use git and Github and are, much more than you are saying, a professional. In this case :

- Use packages which are the most appropriate for your needs, as they are. In this case, I don't see why you can't use my package and build your solution upon it.
- If the most appropriate packages doesn't fit enough your needs, you have to find an another solution. In this case, there are at least two or three Haskell packages for JWT which are much more popular than mine, much more generic and versatile. But, once again, mine should fit your needs as it is. Or, if you insist to use a package, _i.e._ its code inside, you have to ask the author to enhance its package to fit much more yours needs by opening an _issue_ or creating a _pull request_ on the given package repo. I'm sure you know that. In this case, I would be pleased to answer to you and do my best to enhance my work to fit much better its goal, if necessary.

But, indeed, the shortest and trivial answer as I already told you: use packages Open Source developers offers to you as they are, or help to enhance their packages, so the name of Open Source _community_. It's the only way to do things honestly. Or DIY.

All this issue is just about honesty.

So I hope, despite all this, we gonna work together and you gonna use my package.

_N.B._ : Weird, but never talk to a goat before.

**Comment by arowM** [comment]
Thank you. To be honest, I don't remember much about it at the time, but I think the other JWT libraries were designed for client-side authentication with Google . I wanted a way to do server-side authentication.
Now there are libraries that didn't exist back then, and my programming skills have improved since then, so I will consider a better way that fits the OSS philosophy.
